#!/usr/bin/env bash

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
	echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

# Example usage
# In this example it's used to run `npm install` if package.json changed
check_run package.json "npm install"
check_run composer.json "composer install"
chown -R root:root /etc/stool
chown -R stool:stool /etc/stool/storage
chmod -R 755 /etc/stool
stool config:cache
supervisorctl restart stool-deploy
