#!/usr/bin/env bash

source /etc/stool/scripts/helper.sh

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
	echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

check_run package.json "npm install"
check_run composer.json "composer install"
sudo chown -R stool:stool ${ABSOLUTE_PATH}
sudo chmod -R 755 ${ABSOLUTE_PATH}
stool config:cache

sudo supervisorctl restart stool-deploy

sudo cp ${TEMPLATES_PATH}.bash_aliases /home/stool/.bash_aliases

sudo cp ${TEMPLATES_PATH}git/post-merge-this ${ABSOLUTE_PATH}.git/hooks/post-merge
sudo chmod +x ${ABSOLUTE_PATH}.git/hooks/post-merge
check_run ${TEMPLATES_PATH}git/post-merge-this "bash ${ABSOLUTE_PATH}.git/hooks/post-merge"

cp ${TEMPLATES_PATH}update-motd.d/99-stool /etc/update-motd.d/99-stool
sudo chmod +x /etc/update-motd.d/99-stool
